default: &default
  adapter: postgresql
  database: citygram
  encoding: unicode
  host: db
  username: postgres
  url: <%= ENV['DATABASE_URL'] %>
  port: 5432
  pool: 5

development:
  <<: *default
  database: citygram_development

test:
  <<: *default
  database: citygram_test